name = "Create: Agriculture"
author = "danibobani"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15044f7f2b9649446e30ca74156ea5aca0e017bedba0eb86b8156f08a0aea801"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
acceptable-game-versions = ["Forge"]
