name = "Create: Agriculture"
author = "danibobani"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc24a38effcd04384d8cbef8a9c7bd81fff7a34534a3457535c06176eca2b3ec"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
acceptable-game-versions = ["Forge"]
