name = "Create: Agriculture"
author = "danibobani"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce27ead004f4a6dfe583335ef91432141e2fd419ada11c1120b680a37e06f4a3"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
acceptable-game-versions = ["Forge"]
