name = "Create: Agriculture"
author = "danibobani"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a9ed98848407f6b913013a18583fea91c2043420621b69c8372c90e850ec153"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
acceptable-game-versions = ["Forge"]
