name = "Create: Agriculture"
author = "danibobani"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04a346cb39fa79c7267cf1fbe6f01504a1935cc3ebed98d397b68414eff12992"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
acceptable-game-versions = ["Forge"]
