name = "Create: Agriculture"
author = "danibobani"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7ac55a4f43304595c6bd704a5173ac7c302abe87cbe1b9d2fffdb895d9428d8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
acceptable-game-versions = ["Forge"]
